@startuml P2P-PokerGame-StateDiagram
top to bottom direction



[*] --> CommitState : Smart contract created
CommitState --> CommitState : JoinAction (secretHash, sgKeyEncryptedDeck) 
CommitState --> RevealState : No of players reached
note left of CommitState 
    add player
    update deck
    update balance
endnote
RevealState --> RevealState : RevealAction (secret, multiKeyEncryptedDeck)
note left of RevealState
    verify secrethash
    store secret
    update deck
endnote
RevealState --> RevealCards : all secrets revealed
RevealCards --> RevealCards : UnlockCards
note left of RevealCards
    verify vkeys 
    (encrypt other plyrs encrypted and see if match)
endnote
RevealCards --> FirstBetRound : all vkeys posted


FirstBetRound --> FirstBetRound : BettingAction  : SmallBlindBet | Call | Raise Int | Fold | AllIn
note left of FirstBetRound
    update bets
    update players
endnote
FirstBetRound --> Drawing : Betting round ended

Drawing --> Drawing : DrawingAction : NoDraw | Draw [Int] 
note left of Drawing
    update players
    update deck
endnote

Drawing --> RevealCards2 : all secrets revealed
RevealCards2 --> RevealCards2 : UnlockCards
note left of RevealCards2
    verify vkeys 
    (encrypt other plyrs encrypted and see if match)
endnote
RevealCards2 --> SecondBetRound : all vkeys posted


SecondBetRound --> SecondBetRound : Player Action (Bet/Call/Fold/Raise)
note left of SecondBetRound
    update bets
    update players
endnote
SecondBetRound --> Showdown : Betting round ended

Showdown --> Showdown : ShowdownAction :([privatekeys]) 
Showdown --> EndOfHand : All players revealed
note left of EndOfHand
    calculate reward
    update pot and balances
    change dealer
endnote
EndOfHand --> FirstBetRound : continue
EndOfHand --> [*]: close


